# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Push tests
# run-name: ${{ github.actor }} push tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - python: 2.7.18
            plone: 4.3
#          - python: 3.7.14
#            plone: 5.2
#          - python: 3.10.11
#            plone: "6.0"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up pyenv and Python
        uses: "gabrielfalcao/pyenv-action@v14"
        with:
          default: "${{ matrix.python }}"
      - name: Setup Env
        run: |
          sudo apt-get update -qqy
          sudo apt-get install -qqy g++ libpng-dev cmake libqt5widgets5 qttools5-dev
          wget -t 3 -T 60 --waitretry 5 -O zint-2.8.0.tar.gz https://sourceforge.net/projects/zint/files/zint/2.8.0/zint-2.8.0.tar.gz/download
          tar -xf zint-2.8.0.tar.gz
          cd zint-2.8.0
          sudo cmake .
          sudo make
          sudo make install
          cd ..
          pip install --upgrade pip
          pip install -r requirements-${{ matrix.plone }}.txt
      - name: Cache eggs
        uses: actions/cache@v3
        env:
          cache-name: cache-eggs
        with:
          path: ~/buildout-cache/eggs
          key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ matrix.python }}-${{ matrix.plone }}
          restore-keys: ${{ runner.os }}-test-${{ env.cache-name }}-${{ matrix.python }}-${{ matrix.plone }}
      - name: buildout
        run: |
          sed -ie "s#test.cfg#test-${{matrix.plone}}.cfg#" gha.cfg
          buildout -c gha.cfg annotate
          buildout -c gha.cfg
      - name: test
        run: |
          bin/test -t !robot
  coverage:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - python: 2.7.18
            plone: "4.3"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up pyenv and Python
        uses: "gabrielfalcao/pyenv-action@v14"
        with:
          default: "${{ matrix.python }}"
      - name: Setup Env
        run: |
          sudo apt-get update -qqy
          sudo apt-get install -qqy g++ libpng-dev cmake libqt5widgets5 qttools5-dev
          wget -t 3 -T 60 --waitretry 5 -O zint-2.8.0.tar.gz https://sourceforge.net/projects/zint/files/zint/2.8.0/zint-2.8.0.tar.gz/download
          tar -xf zint-2.8.0.tar.gz
          cd zint-2.8.0
          sudo cmake .
          sudo make
          sudo make install
          cd ..
          pip install --upgrade pip
          pip install -r requirements-${{ matrix.plone }}.txt
          pip install --upgrade pip
          pip install -r requirements-${{matrix.plone}}.txt
          pip install -U coveralls coverage
      - name: Cache eggs
        uses: actions/cache@v3
        env:
          cache-name: cache-eggs
        with:
          path: ~/buildout-cache/eggs
          key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ matrix.python }}-${{ matrix.plone }}
          restore-keys: ${{ runner.os }}-test-${{ env.cache-name }}-${{ matrix.python }}-${{ matrix.plone }}
      - name: buildout
        run: |
          sed -ie "s#test.cfg#test-${{matrix.plone}}.cfg#" gha.cfg
          buildout -c gha.cfg
      - name: code-analysis
        run: |
          bin/code-analysis
      - name: test coverage
        run: |
          coverage run bin/test -t !robot
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Coveralls
        run: |
          pip3 install -U pip setuptools --no-cache-dir
          pip3 install -U "coveralls>=3.0.0" coverage==5.3.1 --no-cache-dir
      - name: Publish to Coveralls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          coveralls --service=github
